### ISSUE TITLE
Intercepting NameError

### ISSUE THREAD

**Issue by jayvdb** [dlshriver/intercepts#1]
`module.__getattr__` should be a nice way to catch NameError.
https://stackoverflow.com/questions/2447353/getattr-on-a-module
It would be handy to be able to declare a handler for that on all modules, especially future imports.
Could be a way to allow custom solutions for `__file__` in
https://github.com/indygreg/PyOxidizer/issues/69

**Comment by Nivekiba** [comment]
Rewaking up

**Comment by dlshriver** [comment]
I'm not sure I understand the suggestion, could you clarify? 
- What is the problem you have? Can you provide a small example?
- What prevents intercepts from being applied as it is now?
- What do you think a solution might look like?
