### ISSUE TITLE
Illegal instruction error

### ISSUE THREAD

**Issue by dlshriver** [dlshriver/intercepts#10]
Occasionally, when running the test suite, the run fails with an Illegal instruction error. I've noticed this on several python versions (python 3.9 and 3.10 for sure), and it seems to be easiest to reproduce for me on a raspberry pi.

**Comment by nilnullzip** [comment]
Does this also happen on x86?

And is this behavior specific to the intercept mechanism I submitted, or does it also happen with the original mechanism?

**Comment by dlshriver** [comment]
I don't think it's related to the changes you submitted. I'm pretty sure the problem is between the memory allocation and mprotect call. I've got a possible fix in the works.
