### ISSUE TITLE
Version of python

### ISSUE THREAD

**Issue by Nivekiba** [dlshriver/intercepts#3]
Please, i would like to know why it's not possible to use intercepts for older version of python

In order to contribute to your project if i can

**Comment by dlshriver** [comment]
Which versions of python? I believe we support all of the currently actively maintained versions of cpython.

**Comment by Nivekiba** [comment]
when i try to install **intercepts** with python2 i got errors

**Comment by dlshriver** [comment]
Python 2 is not supported since it has been [retired](https://www.python.org/doc/sunset-python-2/).

**Comment by Nivekiba** [comment]
Ok
