### ISSUE TITLE
Segmentation Fault on simple register call

### ISSUE THREAD

**Issue by pabloduran016** [dlshriver/intercepts#4]
I was playing with this and i wrote a generic handler just to see the arguments

```python
def handler(*args, **kwargs):
    print(args, kwargs)
```

It didnt work correctly and if i put a wrong argument it just crashes

```python
>>> sum([1, 2, 3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument list must be a tuple

>>> sum('hello')
zsh: segmentation fault  python
```

I am on a Macbook Pro with M1 chip and python version 3.9.9

**Comment by dlshriver** [comment]
Sorry, this project is not and has not been maintained for several years. It was created over a year before python3.9 was released and is most likely not compatible with that version of python. I do not plan to fix this issue.
